### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by nmlynch94** [flathub/de.wger.flutter#7]
Upon launch of the application after installing from flathub, I get a white screen on launch along with the error "Invalid argument(s): Failed to lookup symbol 'setLogEnabled': /app/wger/lib/libflutter_linux_gtk.so: undefined symbol: setLogEnabled"

![image](https://github.com/flathub/de.wger.flutter/assets/40608755/f16ecdb2-7f4b-4fcc-94c7-58a43d3049e8)

**Comment by rolandgeider** [comment]
Thanks for the bug report, there is already an issue for this problem here https://github.com/wger-project/flutter/issues/424, we should have a new version out shortly

(closing here)
